#!/bin/bash

# attempt to log public IP address of container
dig +short myip.opendns.com @resolver1.opendns.com

# Add gitlab to hosts file
grep -q -F "$GIT_HOSTS" /etc/hosts  || echo $GIT_HOSTS >> /etc/hosts

# Clone repo to container
git clone -b $GIT_BRANCH $GIT_REPO /var/www/html

#start cron in the background
/usr/sbin/cron -f &

# Start Apache server
/usr/local/bin/apache2-foreground
